name: smk-composite-action-tests

# used on push for testing / development
# on:
#   push:

on:
  pull_request:
    # debug: remove the dev,putting build action on non existent branches for debug
    branches: ['main']
    types: ['opened', 'reopened']
    paths-ignore:
      - openshift/**
      - .vscode/**
      - docs/**
      - .gitignore
      - LICENSE
      - open-api.json
      - readme.md
      - helm-charts
      - code_of_conduct.md
      
jobs:
  # This workflow contains a single job called "build"
  buildjob:
    defaults:
      run:
        shell: bash

    name: 'Build smk-clean-bc container image'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      OPENSHIFT_SERVER_URL: ${{secrets.OPENSHIFT_SERVER_URL}}
      OPENSHIFT_TOKEN_DEV: ${{secrets.OPENSHIFT_TOKEN_DEV}}
      OPENSHIFT_TOKEN_PROD: ${{secrets.OPENSHIFT_TOKEN_PROD}}
      GHCR_USER: ${{ secrets.GHCR_USER }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      DEBUG_DEPLOY: false
      
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
      if: env.DEBUG_DEPLOY == 'false'
      id: checkout
      with:
        fetch-depth: 0

    - name: Building image
      uses: bcgov/smk-actions/smk-build@main
      id: buildSMKImage
      with:
        OPENSHIFT_SERVER_URL: ${{ secrets.OPENSHIFT_SERVER_URL }}
        OPENSHIFT_TOKEN_DEV: ${{ secrets.OPENSHIFT_TOKEN_DEV }}
        GHCR_USER: ${{ secrets.GHCR_USER }}
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        DOCKER_REGISTRY: 'ghcr.io'

    - name: deploying dev
      uses: bcgov/smk-actions/smk-deploy@main
      id: deploySMKContainer
      with:
        OPENSHIFT_SERVER_URL: ${{ secrets.OPENSHIFT_SERVER_URL }}
        OPENSHIFT_TOKEN_DEV: ${{ secrets.OPENSHIFT_TOKEN_DEV }}
        GHCR_USER: ${{ secrets.GHCR_USER }}
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        DOCKER_REGISTRY: 'ghcr.io'
        PR_REVIEWERS: '["michaelpnelson"]'
        PR_MENTIONS: '["michaelpnelson"]'

    # Add configMap with routing api key to the deployment config
    - name: Login to Dev Openshift
      id: oc-login
      shell: bash
      env:
        OPENSHIFT_SERVER_URL: ${{ secrets.OPENSHIFT_SERVER_URL }}
        OPENSHIFT_TOKEN_DEV: ${{ secrets.OPENSHIFT_TOKEN_DEV }}
      run: |
        echo ----- OC-LOGIN -----
        # get oc client
        curl https://downloads-openshift-console.apps.silver.devops.gov.bc.ca/amd64/linux/oc.tar -o oc.tar
        tar -xvf oc.tar
        curdir=$(pwd)
        PATH=$curdir:$PATH
        oc login --token=$OPENSHIFT_TOKEN_DEV --server=$OPENSHIFT_SERVER_URL
        oc patch deployment smk-clean-bc-dp -p '[{"op":"add","path":"/spec/template/spec/containers/0/volumeMounts","value":[{"name":"config-volume","mountPath":"/srv/config"}]},{"op":"add","path":"/spec/template/spec/columes","value":{"name":"config-volume","configMap":{"name":"smk-clean-bc-dev-api-key","items":[{"key":"api-key","path":"route-planner.json"}]}}}]' --type json
